### ISSUE TITLE
Rutorrent Plugin issues since last update

### ISSUE THREAD

**Issue by maticks81** [linuxserver/docker-rutorrent#112]
I have been seeing issues with the plugins loading since the last update.

09.04.2019 10:48:45] _task: Plugin will not work. Webserver user can't access external program (pgrep).
[09.04.2019 10:48:45] _cloudflare: Plugin will not work. Webserver user can't access external program (python).
[09.04.2019 10:48:45] create: Plugin will not work. It requires plugin(s) _task
[09.04.2019 10:48:45] unpack: Plugin will not work. It requires plugin(s) _task
[09.04.2019 10:48:45] extratio: Plugin will not work. It requires plugin(s) ratio,throttle
[09.04.2019 10:48:45] mediainfo: Plugin will not work. It requires plugin(s) _task
[09.04.2019 10:48:45] screenshots: Plugin will not work. It requires plugin(s) _task
[09.04.2019 10:48:45] spectrogram: Plugin will not work. It requires plugin(s) _task

Checked permissions everything is set correct 777 and correct user.

in the rutorrent.log file i see these errors.

[09.04.19 08:56:31] <?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>execute.capture</methodName><params>
<param><value><string></string></value></param>
<param><value><string>sh</string></value></param>
<param><value><string>-c</string></value></param>
<param><value><string>/usr/bin/id -u ; /usr/bin/id -G ; echo ~ </string></value></param>
</params></methodCall>
[09.04.19 08:56:31] Status: 200 OK
Content-Type: text/xml
Content-Length: 324

<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<fault>
<value><struct>
<member><name>faultCode</name>
<value><i4>-503</i4></value></member>
<member><name>faultString</name>
<value><string>ExecFile::execute(...) Pipe creation failed.</string></value></member>
</struct></value>
</fault>
</methodResponse>

**Comment by kkasberg** [comment]
I am also getting a python error (that python cannot be found).

[09.04.2019 11:25:28] WebUI started.
[09.04.2019 11:25:32] _cloudflare: Plugin will not work. Webserver user can't access external program (python).
[09.04.2019 11:25:32] _task: Plugin will not work. Webserver user can't access external program (pgrep).
[09.04.2019 11:25:32] create: Plugin will not work. It requires plugin(s) _task
[09.04.2019 11:25:32] unpack: Plugin will not work. It requires plugin(s) _task
[09.04.2019 11:25:32] mediainfo: Plugin will not work. It requires plugin(s) _task
[09.04.2019 11:25:32] screenshots: Plugin will not work. It requires plugin(s) _task
[09.04.2019 11:25:32] spectrogram: Plugin will not work. It requires plugin(s) _task

**Comment by j0nnymoe** [comment]
Information on how you deployed the container please - host os / docker run command etc

**Comment by kkasberg** [comment]
host OS is ubuntu 18.04 with the following config.

```
docker create --name=rutorrent \
-v <path to config>:/config \
-v <path to download>:/downloads \
-e PGID=1000 -e PUID=1000 \
-e TZ=America/New_York \
-p 8080:80 -p 5000:5000 \
-p 51414:51414 -p 6881:6881/udp \
linuxserver/rutorrent
```

**Comment by j0nnymoe** [comment]
You need to replace the `<path to X>` with your own file locations

**Comment by kkasberg** [comment]
I did, I just removed them for privacy.   

```
docker create --name=rutorrent \
-v /opt/rutorrent/config/:/config \
-v /home/kevin/downloads/:/home/kevin/downloads \
-e PGID=1000 -e PUID=1000 \
-e TZ=America/New_York \
-p 8080:80 -p 5000:5000 \
-p 51414:51414 -p 6881:6881/udp \
linuxserver/rutorrent
```

**Comment by guillaumelachaud** [comment]
For what it's worth, I don't think that matters much for the problem here.

It looks like
https://github.com/linuxserver/docker-rutorrent/commit/741d6ec4c7321ea5e5cb66b5477d14322c1ade3e
switched from Alpine to nginx as the base image. Does the nginx come with
python dependencies installed?

**Comment by j0nnymoe** [comment]
No I know it might not matter specifically but we ask for these details when a user opens a ticket so we can understand the environment it's in. 

I'll get someone to check it out

**Comment by bordot** [comment]
Having this exact same issue on my fresh install of Ubuntu 16.04. Any help would be appreciated!

Edit: Reverting to DockerHub version "1b9c6355-ls23" from 24 days ago resolved the issues for me.

**Comment by maticks81** [comment]
i am running Ubuntu 18.10.

docker create --name=rutorrent \
-v /home/docker/rutorrent/config:/config \
-v /home/docker/rutorrent/downloads:/downloads \
-e PGID=1000 -e PUID=1000 \
-e TZ=Australia/Sydney \
-p 8080:80 -p 5000:5000 \
-p 51414:51414 -p 6881:6881/udp \
linuxserver/rutorrent

nothing has been upgraded on my server all that happened is a pull of the rutorrent docker container on latest around a week ago broke some plugins in the log file on its restart.

The docker container i have restarted a few times before the docker update was done.

I restart my docker container with "sudo docker restart rutorrent"
My configs and permissions are fine.

**Comment by maticks81** [comment]
as per the patch information i added into /rutorrent/config/rutorrent/settings/config.php
  "pgrep" => '/usr/bin/pgrep',                    // Something like /usr/bin/pgrep. If empty, will be found in PATH.
  "python" => '/usr/bin/python3',                 // Something like /usr/bin/python3. If empty, will be found in PATH.

that fixed pgrep but not python.
Still get this error
[11.04.2019 19:29:23] WebUI started.
[11.04.2019 19:29:23] _cloudflare: Plugin will not work. Webserver user can't access external program (python).

logging into the docker, this could be why...
root@9839e1e101b0:/# find / -name python -print
root@9839e1e101b0:/#

**Comment by maticks81** [comment]
i issued "apk add python3" in the docker container that fixed it.

**Comment by kkasberg** [comment]
This is still not working after the latest build.

I updated my config.php to includes the paths specified on github.

```
        $pathToExternals = array(
                "php"   => '/usr/bin/php7',                     // Something like /usr/bin/php. If empty, will be found in PATH.
                "pgrep" => '/usr/bin/pgrep',                    // Something like /usr/bin/pgrep. If empty, will be found in PATH.
                "python" => '/usr/bin/python3',                 // Something like /usr/bin/python3. If empty, will be found in PATH.
                "curl"  => '/usr/bin/curl',                     // Something like /usr/bin/curl. If empty, will be found in PATH.
                "gzip"  => '/usr/bin/gzip',                     // Something like /usr/bin/gzip. If empty, will be found in PATH.
                "id"    => '/usr/bin/id',                       // Something like /usr/bin/id. If empty, will be found in PATH.
                "stat"  => '/bin/stat',                 // Something like /usr/bin/stat. If empty, will be found in PATH.
        );
```

**Comment by tobbenb** [comment]
What does the find command maticks81 posted show?

**Comment by kkasberg** [comment]
Nothing, you have to search for python3 for it to return something.

**Comment by tobbenb** [comment]
I was asking you to search for python3

**Comment by kkasberg** [comment]
find / -name python3 -print
/usr/bin/python3

**Comment by tobbenb** [comment]
So python is there. Did you change the paths in config.php as maticks81 did?

**Comment by kkasberg** [comment]
Yes, you can see my config.php block that was updated above.

**Comment by kkasberg** [comment]
Yes, you can see my config.php block that was updated above.

**Comment by kkasberg** [comment]
Yes, you can see my config.php block that was updated above.

**Comment by tobbenb** [comment]
And it's all correct?
Post the errors you get also.

**Comment by kkasberg** [comment]
I am getting the following errors:

```
[11.04.2019 12:10:41] WebUI started.
[11.04.2019 12:10:44] _cloudflare: Plugin will not work. Webserver user can't access external program (python).
[11.04.2019 12:10:44] _task: Plugin will not work. Webserver user can't access external program (pgrep).
[11.04.2019 12:10:44] create: Plugin will not work. It requires plugin(s) _task
[11.04.2019 12:10:44] unpack: Plugin will not work. It requires plugin(s) _task
[11.04.2019 12:10:44] mediainfo: Plugin will not work. It requires plugin(s) _task
[11.04.2019 12:10:44] screenshots: Plugin will not work. It requires plugin(s) _task
[11.04.2019 12:10:44] spectrogram: Plugin will not work. It requires plugin(s) _task
```

This is the exact copy from my config.php, which looks to be correct.

```
        $pathToExternals = array(
                "php"   => '/usr/bin/php7',                     // Something like /usr/bin/php. If empty, will be found in PATH.
                "pgrep" => '/usr/bin/pgrep',                    // Something like /usr/bin/pgrep. If empty, will be found in PATH.
                "python" => '/usr/bin/python3',                 // Something like /usr/bin/python3. If empty, will be found in PATH.
                "curl"  => '/usr/bin/curl',                     // Something like /usr/bin/curl. If empty, will be found in PATH.
                "gzip"  => '/usr/bin/gzip',                     // Something like /usr/bin/gzip. If empty, will be found in PATH.
                "id"    => '/usr/bin/id',                       // Something like /usr/bin/id. If empty, will be found in PATH.
                "stat"  => '/bin/stat',                 // Something like /usr/bin/stat. If empty, will be found in PATH.
        );

```

**Comment by tobbenb** [comment]
I have no idea how it's supposed to look, but since maticks81 got it working, you are not adding the correct bits.

**Comment by kkasberg** [comment]
I deleted the volumes and re-created the docker container and am still getting the same error.   This should be pulling fresh settings directly from the docker hub image.

**Comment by kkasberg** [comment]
I found the issue.   I was editing the wrong file.   You need to update the data directory at 
config/rutorrent/settings/config.php

**Comment by maticks81** [comment]
you are definitely editing the wrong config.php file or you didn't issue a docker restart on that container after editing it.
What you should have is the pgrep issue go away and only the python one remaining if you get the correct config.php.
I did also do a search for python3 and python both were missing.
after issuing "apk add python3" and restarting the container that fixed this problem.

Python did disappear from the container but its not that hard to add it back in.

**Comment by peavers** [comment]
Is there any plans to properly fix this or should I fork?

**Comment by maticks81** [comment]
you need to edit your config.php file adding in these two lines.
You should be able to find this file in config/rutorrent/settings/config.php

 $pathToExternals = array(
                "pgrep" => '/usr/bin/pgrep',                    // Something like /usr/bin/pgrep. If empty, will be found in PATH.
                "python" => '/usr/bin/python3',                 // Something like /usr/bin/python3. If empty, will be found in PATH.

Then restart your docker and _task will pickup pgrep and unpack will work fine.

**Comment by peavers** [comment]
I fully understand how to manually fix this myself, but shouldn't it be part of the container?

**Comment by maticks81** [comment]
I would imagine it will be patched in a future push.

**Comment by peavers** [comment]
Exactly, but it looks as if the maintainers don't really have an interest in solving this as it's a trivial fix and there have been a number of releases since this was raised. Hence my original question. Happy to do it myself if nobody else will.

**Comment by sparklyballs** [comment]
the lines have been added to the default config.php that ships with the image, so new users will not see this particular issue.

https://github.com/linuxserver/docker-rutorrent/blob/master/root/defaults/rutorrent-conf/config.php#L44

but to "patch" it for existing users would not be viable, for a single instance like this yes, but given the fluid nature of changes that can affect this image, we would end up with an init file as long as the bible.

existing users can edit in the changes via the files in the config mount, that is one of its purposes... to allow editing.

**Comment by guillaumelachaud** [comment]
I completely agree that it users shouldn't have to do a manual fix in order for a basic feature to work. That being said, "new users" of the image are not experiencing the issue I think.

The way I fixed it properly for me, is that instead of editing config.php, I deleted it. When you restart the container, rutorrent will find python3 in the proper place and will write config.php properly. If you edited config.php already for other needs, than you need to manually edit the paths to adjust it. Otherwise, just delete it. If you start from scratch, everything should be ok.

EDIT: @sparklyballs replied faster than me :-)

**Comment by Sn0wCrack** [comment]
It looks like this is still happening for the _cloudflare plugin, seem to be getting the following on a fresh install from today:
```
_cloudflare plugin: cloudscraper module can't be loaded in Python
```

Tried installing it in the container manually but looks like the cloudscraper package needs gcc in order to be installed via pip (due to it needing to compile a brotli module)

Ran the following and it seems to now be fine
```bash
apk add gcc g++ python3-dev libc-dev
pip3 install cloudscraper
```

**Comment by sparklyballs** [comment]
@Sn0wCrack , you shouldn't necro closed threads. 

although it is technically the same issue, if you add this to a closed thread, it will not be seen when we look at open issues on this image.

the only way it get's picked up is if someone is lucky enough to see the email alert. 

this pr #116 addresses the issue.
