### ISSUE TITLE
unRAID server - after last updates ... unable to add torrent file

### ISSUE THREAD

**Issue by DrMythnick** [linuxserver/docker-rutorrent#131]
Hi,

I have actually 2 issues:

1st
****
[09.04.2019 12:25:51] WebUI started.
[09.04.2019 12:25:54] _task: Plugin will not work. Webserver user can't access external program (pgrep).
[09.04.2019 12:25:54] _cloudflare: Plugin will not work. Webserver user can't access external program (python).
[09.04.2019 12:25:54] create: Plugin will not work. It requires plugin(s) _task
[09.04.2019 12:25:54] unpack: Plugin will not work. It requires plugin(s) _task
[09.04.2019 12:25:54] mediainfo: Plugin will not work. It requires plugin(s) _task
[09.04.2019 12:25:54] screenshots: Plugin will not work. It requires plugin(s) _task
[09.04.2019 12:25:54] spectrogram: Plugin will not work. It requires plugin(s) _task
****

> i fixed this one by adding the bellow paths to ( /config/rutorrent/settings/config.php ) :

"""
"pgrep" => '/usr/bin/pgrep', // Something like /usr/bin/pgrep. If empty, will be found in PATH.
"python" => '/usr/bin/python3', // Something like /usr/bin/python3. If empty, will be found in PATH.
"""

2nd
****
i try to add a torrent and it seats at 80% upload for 1 minute and after it gives me this error :

[29.07.2019 12:59:30] JS error: [http://192.168.1.*:50080/js/content.js : 72] Uncaught SecurityError: Blocked a frame with origin "http://192.168.1.*:50080" from accessing a cross-origin frame.

****

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by nomandera** [comment]
To clarify this is fixed in master but not in existing installs:

https://github.com/linuxserver/docker-rutorrent/blob/master/root/defaults/rutorrent-conf/config.php#L44-L45

which is correct

```
root@e70da2c61428:/# which pgrep
/usr/bin/pgrep
root@e70da2c61428:/# which python3
/usr/bin/python3
```

**Comment by thelamer** [comment]
If anyone hits this via Google @anoma is correct, make those changes to your config file with the container shut down. 
We will not be editing users configuration files from the container only ever copy a default one from a clean container.

**Comment by DrMythnick** [comment]
and the second issue ? the second issue is still present even after installing a second new container on the same unRAID server.

also, strange is that the a new docker container works ok on LXC Proxmox ... :(

**Comment by thelamer** [comment]
I cannot duplicate that issue a new container is 100% functional for me and I would suspect other users of this container as there are no other mentions of this error in our issues. That wildcard looks out of place in the URL though. 
If you need support please try our Discord, Github is for bug reports and feature requests: 
https://discord.gg/YWrKVTn
